/**
 * 内置项目模板注册表
 */

export interface ProjectTemplate {
  id: string;
  name: string;
  description: string;
  techStack: string;
  files: Record<string, string>; // 文件路径 -> 内容
}

/** 内置模板列表 */
export const TEMPLATES = new Map<string, ProjectTemplate>([
  [
    "nextjs",
    {
      id: "nextjs",
      name: "Next.js 14 + TypeScript",
      description: "Next.js App Router, ESLint, Tailwind CSS",
      techStack: "nextjs",
      files: {
        "package.json": JSON.stringify(
          {
            name: "{{projectName}}",
            version: "0.1.0",
            private: true,
            scripts: {
              dev: "next dev",
              build: "next build",
              start: "next start",
              lint: "next lint",
              test: "vitest --run",
            },
            dependencies: {
              next: "^14.0.0",
              react: "^18.0.0",
              "react-dom": "^18.0.0",
            },
            devDependencies: {
              "@types/node": "^20.0.0",
              "@types/react": "^18.0.0",
              typescript: "^5.0.0",
              eslint: "^8.0.0",
              "eslint-config-next": "^14.0.0",
              tailwindcss: "^3.0.0",
              vitest: "^1.0.0",
            },
          },
          null,
          2,
        ),
        "tsconfig.json": JSON.stringify(
          {
            compilerOptions: {
              target: "ES2017",
              lib: ["dom", "dom.iterable", "esnext"],
              allowJs: true,
              skipLibCheck: true,
              strict: true,
              noEmit: true,
              esModuleInterop: true,
              module: "esnext",
              moduleResolution: "bundler",
              resolveJsonModule: true,
              isolatedModules: true,
              jsx: "preserve",
              incremental: true,
              plugins: [{ name: "next" }],
              paths: { "@/*": ["./src/*"] },
            },
            include: ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
            exclude: ["node_modules"],
          },
          null,
          2,
        ),
        "src/app/page.tsx": `export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <h1 className="text-4xl font-bold">Welcome to {{projectName}}</h1>
    </main>
  );
}
`,
        "src/app/layout.tsx": `import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "{{projectName}}",
  description: "Generated by AI Dev Pipeline",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
`,
        "src/app/globals.css": `@tailwind base;
@tailwind components;
@tailwind utilities;
`,
        ".gitignore": `node_modules/
.next/
out/
.env*.local
`,
      },
    },
  ],
  [
    "fastapi",
    {
      id: "fastapi",
      name: "Python + FastAPI",
      description: "FastAPI, uvicorn, pytest, ruff",
      techStack: "fastapi",
      files: {
        "pyproject.toml": `[project]
name = "{{projectName}}"
version = "0.1.0"
description = "{{description}}"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.100.0",
    "uvicorn[standard]>=0.23.0",
    "pydantic>=2.0.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-asyncio>=0.21.0",
    "ruff>=0.1.0",
    "httpx>=0.24.0",
]

[tool.ruff]
line-length = 100
target-version = "py311"

[tool.pytest.ini_options]
asyncio_mode = "auto"
`,
        "src/__init__.py": "",
        "src/main.py": `from fastapi import FastAPI

app = FastAPI(title="{{projectName}}")


@app.get("/")
async def root():
    return {"message": "Hello from {{projectName}}"}


@app.get("/health")
async def health():
    return {"status": "ok"}
`,
        "tests/__init__.py": "",
        "tests/test_main.py": `from fastapi.testclient import TestClient
from src.main import app

client = TestClient(app)


def test_root():
    response = client.get("/")
    assert response.status_code == 200
    assert "message" in response.json()


def test_health():
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["status"] == "ok"
`,
        ".gitignore": `__pycache__/
*.py[cod]
.venv/
.env
.pytest_cache/
.ruff_cache/
`,
      },
    },
  ],
  [
    "gin",
    {
      id: "gin",
      name: "Go + Gin",
      description: "Gin web framework",
      techStack: "gin",
      files: {
        "go.mod": `module {{projectName}}

go 1.21

require github.com/gin-gonic/gin v1.9.1
`,
        "main.go": `package main

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

func main() {
	r := gin.Default()

	r.GET("/", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{
			"message": "Hello from {{projectName}}",
		})
	})

	r.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{
			"status": "ok",
		})
	})

	r.Run(":8080")
}
`,
        "main_test.go": `package main

import (
	"net/http"
	"net/http/httptest"
	"testing"

	"github.com/gin-gonic/gin"
)

func TestHealthEndpoint(t *testing.T) {
	gin.SetMode(gin.TestMode)
	r := gin.Default()
	r.GET("/health", func(c *gin.Context) {
		c.JSON(http.StatusOK, gin.H{"status": "ok"})
	})

	req, _ := http.NewRequest("GET", "/health", nil)
	w := httptest.NewRecorder()
	r.ServeHTTP(w, req)

	if w.Code != http.StatusOK {
		t.Errorf("Expected status 200, got %d", w.Code)
	}
}
`,
        ".gitignore": `bin/
*.exe
*.test
.env
`,
      },
    },
  ],
]);

/** 获取模板 */
export function getTemplate(id: string): ProjectTemplate | undefined {
  return TEMPLATES.get(id);
}

/** 获取所有模板 ID */
export function getTemplateIds(): string[] {
  return Array.from(TEMPLATES.keys());
}

/** 渲染模板文件内容 */
export function renderTemplateFiles(
  template: ProjectTemplate,
  variables: Record<string, string>,
): Record<string, string> {
  const result: Record<string, string> = {};
  for (const [filePath, content] of Object.entries(template.files)) {
    let rendered = content;
    for (const [key, value] of Object.entries(variables)) {
      rendered = rendered.replace(new RegExp(`\\{\\{${key}\\}\\}`, "g"), value);
    }
    result[filePath] = rendered;
  }
  return result;
}
